# This project fundamentally depends on Linux cgroups via Firejail, and
# is currently only actively tested on 64-bit x86 targets, so silence
# warnings about transitive dependencies specific to other targets.
[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
]

[licenses]
allow = ["MIT", "BSL-1.0", "Apache-2.0", "Unicode-DFS-2016", "Zlib"]

[bans]
multiple-versions = "allow"
wildcards = "deny"
