version: 2
updates:
    - package-ecosystem: "cargo"
      directory: "/verify_files" # Location of package manifests
      schedule:
          interval: "weekly"
      reviewers:
          - "ssokolow"
