# TODO: Make it clear in the documentation that a "bin/exe may be any of
# multiple formats" fallback chain is implemented by having multiple filetypes
# with the same extension/header, not specifying a list of handlers in a single
# filetype. (That latter one is for making it easier to satisfy the system
# requirements by allowing users to install whatever's easiest.)
#
# (Do I need something more than `container` for ensuring correct precedence
# in real-world situations when more than one filetype matches something and
# both handlers can process the type? Is such a situation a big enough hazard
# to worry about it?)

# Each filetype must have a unique identifer for two reasons:
#
# 1. It allows the TOML parser to handle for preventing duplicate  IDs.
# 2. It ensures that later validation stages which may not have easy access to
#    line numbers will have something to use in error messages.
#
# By convention, the identifier is the most natural single-word name for the
# file format, in lowercase alphanumeric form (eg. jpeg, mp3, 7zip, etc.) but,
# if more than one format has the same name, do not hesitate to use underscores
# to avoid ambiguity. (eg. ms_cab)

[filetype.3gpp]
description = "MPEG-4 Part 12 Media (3GPP)"
handler = "ffmpeg"
extension = "3gp"

[filetype.3gpp2]
description = "MPEG-4 Part 12 Media (3GPP2)"
handler = "ffmpeg"
extension = "3g2"

[filetype.7zip]
description = "7-Zip archive"
handler = "p7zip"
header = [ 55, 122, 188, 175, 39, 28 ]
extension = "7z"

[filetype.aac]
description = "AAC (ADTS Stream)"
handler = "ffmpeg"
extension = "aac"

[filetype.aifc]
description = "AIFF Audio (Compressed)"
handler = "ffmpeg"
extension = "aifc"

[filetype.aiff]
description = "AIFF Audio"
handler = "ffmpeg"
extension = [ "aif", "aiff" ]

[filetype.ape]
description = "Monkey's Audio"
handler = "ffmpeg"
extension = "ape"

[filetype.arj]
description = "ARJ archive"
handler = "arj"
extension = "arj"

[filetype.asf]
description = "Microsoft ASF"
handler = "ffmpeg"
header = [ 48, 38, 178, 117, 142, 102, 207, 17, 166, 217, 0, 170, 0, 98, 206, 108 ]
extension = "asf"

[filetype.avi]
description = "Microsoft AVI Video"
handler = "ffmpeg"
extension = "avi"

[filetype.bin]
description = ".bin"
handler = "bin"
extension = "bin"

[filetype.binhex4]
description = "BinHex4"
handler = "binhex"
extension = "hqx"

[filetype.bmp]
description = "Microsoft Device-Independent Bitmap Image"
handler = "pil"
extension = [ "bmp", "dib" ]

[filetype.bzip2]
description = "BZip2 compressed"
handler = "bz2"
header = [ 66, 90, 104 ]
extension = "bz2"

# TODO: Remove `handler` lines which just duplicate what's inherited from
#       `container` once I no longer need to support the Python version.
[filetype.cb7]
description = "Comic Book Archive (7-Zip)"
handler = "p7zip"
container = "7zip"
extension = "cb7"

[filetype.cbr]
description = "Comic Book Archive (RAR)"
handler = "unrar"
container = "rar"
extension = "cbr"

[filetype.cbt]
description = "Comic Book Archive (Tar)"
handler = "tar"
container = "tar"
extension = "cbt"

[filetype.cbz]
description = "Comic Book Archive (Zip)"
handler = "zip"
container = "zip"
extension = "cbz"

[filetype.dashtoc]
description = "Dash/Zeal Docset Table of Contents"
handler = "json"
extension = "dashtoc"

[filetype.dcx]
description = "Multi-page ZSoft PC Paintbrush Image"
handler = "pil"
multipage = true
extension = "dcx"

[filetype.deb]
description = "Debian Package"
handler = "p7zip"
extension = "deb"

[filetype.dmg]
description = "Apple DMG Disk Image"
handler = "p7zip"
extension = "dmg"

[filetype.docm]
description = "Macro-enabled OOXML Document"
handler = "zip"
container = "zip"
extension = "docm"

[filetype.docx]
description = "OOXML Document"
handler = "zip"
container = "zip"
extension = "docx"

[filetype.epub]
description = "ePub e-book"
handler = "zip"
container = "zip"
extension = "epub"

[filetype.f4a]
description = "FLV Audio"
handler = "ffmpeg"
extension = "f4a"

[filetype.f4b]
description = "FLV Audiobook"
handler = "ffmpeg"
extension = "f4b"

[filetype.f4v]
description = "FLV Video"
handler = "ffmpeg"
extension = "f4v"

[filetype.flac]
description = "FLAC Audio"
handler = "flac"
extension = "flac"

[filetype.flic]
description = "Autodesk FLIC Animation"
handler = "pil"
extension = [ "fli", "flc" ]

[filetype.flv]
description = "Flash Video"
handler = "ffmpeg"
extension = "flv"

[filetype.gif]
description = "GIF Image"
handler = "pil"
header = [ [ 71, 73, 70, 56, 55, 97 ], [ 71, 73, 70, 56, 57, 97 ] ]
extension = "gif"

[filetype.gzip]
description = "GZip compressed"
handler = "gzip"
header = [ 31, 139 ]
extension = "gz"

[filetype.innosetup_exe]
description = "Inno Setup Installer"
handler = "innoextract"
extension = "exe"

[filetype.jar]
description = "Java ARchive"
handler = "zip"
container = "zip"
extension = "jar"

[filetype.jpeg]
description = "JPEG/JFIF Image"
handler = "pil"
header = [ 255, 216, 255 ]
extension = [ "jfi", "jfif", "jif", "jpe", "jpeg", "jpg" ]

[filetype.jpeg2k]
description = "JPEG 2000 Image"
handler = "pil"
extension = [ "j2k", "jp2", "jpf", "jpx" ]

[filetype.json]
description = "JSON Data"
handler = "json"
extension = "json"

[filetype.lha]
description = "LHA archive"
handler = "p7zip"
extension = [ "lha", "lzh" ]

[filetype.lzip]
description = "Lzip compressed"
handler = "lzip"
header = [ 76, 90, 73, 80 ]
extension = "lz"

[filetype.lzma]
description = ".lzma"
handler = "lzma"
extension = "lzma"

[filetype.lzx]
description = "LZX archive"
handler = "lsar"
extension = "lzx"

[filetype.m4a]
description = "MPEG-4 Part 14 Audio"
handler = "ffmpeg"
extension = "m4a"

[filetype.m4b]
description = "MPEG-4 Part 14 Audiobook"
handler = "ffmpeg"
extension = "m4b"

[filetype.m4r]
description = "MPEG-4 Part 14 Ringtone"
handler = "ffmpeg"
extension = "m4r"

[filetype.m4v]
description = "MPEG-4 Part 14 Video"
handler = "ffmpeg"
extension = "m4v"

[filetype.mk3d]
description = "Matroska Video (3D)"
handler = "ffmpeg"
extension = "mk3d"

[filetype.mka]
description = "Matroska Audio"
handler = "ffmpeg"
extension = "mka"

[filetype.mkv]
description = "Matroska Video"
handler = "ffmpeg"
extension = "mkv"

[filetype.mpeg_ts]
description = "MPEG Transport Stream"
handler = "ffmpeg"
extension = "ts"

[filetype.mpeg_tsa]
description = "MPEG Transport Stream Audio"
handler = "ffmpeg"
extension = "tsa"

[filetype.mpeg_tsv]
description = "MPEG Transport Stream Video"
handler = "ffmpeg"
extension = "tsv"

[filetype.ms_cab]
description = "Microsoft CAB"
handler = "cabextract"
extension = "cab"

[filetype.ms_cursor]
description = "Microsoft Cursor"
handler = "pil"
multipage = true
extension = "cur"

[filetype.ms_ico]
description = "Microsoft Icon"
handler = "pil"
multipage = true
extension = "ico"

[filetype.mov]
description = "Quicktime Video"
handler = "ffmpeg"
extension = "mov"

[filetype.mp1]
description = "MPEG Layer 1 Audio"
handler = "ffmpeg"
extension = "mp1"

[filetype.mp2]
description = "MPEG Layer 2 Audio"
handler = "ffmpeg"
extension = "mp2"

[filetype.mp3]
description = "MPEG Layer 3 Audio"
handler = "ffmpeg"
extension = "mp3"

[filetype.mp4]
description = "MPEG-4 Part 14 Video"
handler = "ffmpeg"
extension = "mp4"

[filetype.mpeg]
description = "MPEG Video"
handler = "ffmpeg"
extension = [ "mpe", "mpeg", "mpg" ]

[filetype.msi]
description = "MSI Installer"
handler = "p7zip"
extension = "msi"

[filetype.musepack]
description = "Musepack Audio"
handler = "ffmpeg"
extension = [ "mp+", "mpc", "mpp" ]

[filetype.odb]
description = "ODF Database"
handler = "zip"
container = "zip"
extension = "odb"

[filetype.odc]
description = "ODF Chart"
handler = "zip"
container = "zip"
extension = "odc"

[filetype.odf]
description = "ODF Formula"
handler = "zip"
container = "zip"
extension = "odf"

[filetype.odg]
description = "ODF Drawing"
handler = "zip"
container = "zip"
extension = "odg"

[filetype.odi]
description = "ODF Image"
handler = "zip"
container = "zip"
extension = "odi"

[filetype.odm]
description = "ODF Master Document"
handler = "zip"
container = "zip"
extension = "odm"

[filetype.odp]
description = "ODF Presentation"
handler = "zip"
container = "zip"
extension = "odp"

[filetype.ods]
description = "ODF Spreadsheet"
handler = "zip"
container = "zip"
extension = "ods"

[filetype.odt]
description = "ODF Text Document"
handler = "zip"
container = "zip"
extension = "odt"

[filetype.oga]
description = "Ogg containing audio (.oga)"
handler = "ffmpeg"
extension = "oga"

[filetype.ogg]
description = "Ogg Vorbis (.ogg)"
handler = "ffmpeg"
extension = "ogg"

[filetype.ogm]
description = "OGM (Ogg, Unofficial)"
handler = "ffmpeg"
extension = "ogm"

[filetype.ogv]
description = "Ogg containing video (.ogv)"
handler = "ffmpeg"
extension = "ogv"

[filetype.ogx]
description = "Ogg (unspecified) (.ogx)"
handler = "ffmpeg"
extension = "ogx"

[filetype.opus]
description = "Opus Audio"
handler = "ffmpeg"
extension = "opus"

[filetype.otc]
description = "ODF Chart Template"
handler = "zip"
container = "zip"
extension = "otc"

[filetype.otf]
description = "ODF Formula Template"
handler = "zip"
container = "zip"
extension = "otf"

[filetype.otg]
description = "ODF Drawing Template"
handler = "zip"
container = "zip"
extension = "otg"

[filetype.oth]
description = "ODF Web Page Template"
handler = "zip"
container = "zip"
extension = "oth"

[filetype.oti]
description = "ODF Image Template"
handler = "zip"
container = "zip"
extension = "oti"

[filetype.otp]
description = "ODF Presentation Template"
handler = "zip"
container = "zip"
extension = "otp"

[filetype.ots]
description = "ODF Spreadsheet Template"
handler = "zip"
container = "zip"
extension = "ots"

[filetype.ott]
description = "ODF Text Document Template"
handler = "zip"
container = "zip"
extension = "ott"

[filetype.pbm]
description = "NetPBM Portable Bitmap Image"
handler = "pil"
extension = "pbm"

[filetype.pcx]
description = "ZSoft PC Paintbrush Image"
handler = "pil"
extension = "pcx"

[filetype.pdf]
description = "PDF Document"
handler = "pdftotext"
header = [ 37, 80, 68, 70 ]
extension = "pdf"

[filetype.pgm]
description = "NetPBM Portable Graymap Image"
handler = "pil"
extension = "pgm"

[filetype.png]
description = "PNG Image"
handler = "pil"
header = [ 137, 80, 78, 71, 13, 10, 26, 10 ]
extension = "png"

[filetype.potm]
description = "Macro-enabled OOXML Presentation Template"
handler = "zip"
container = "zip"
extension = "potm"

[filetype.ppm]
description = "NetPBM Portable Pixmap Image"
handler = "pil"
extension = "ppm"

[filetype.ppsx]
description = "OOXML Presentation (Self-Starting)"
handler = "zip"
container = "zip"
extension = "ppsx"

[filetype.pptm]
description = "Macro-enabled OOXML Presentation"
handler = "zip"
container = "zip"
extension = "pptm"

[filetype.pptx]
description = "OOXML Presentation"
handler = "zip"
container = "zip"
extension = "pptx"

[filetype.py]
description = "Python Source Code"
handler = "py"
extension = "py"

[filetype.pyc]
description = "Python Bytecode"
handler = "ignore"
extension = "pyc"

[filetype.pyo]
description = "Python Bytecode (Optimized)"
handler = "ignore"
extension = "pyo"

[filetype.ra]
description = "RealAudio"
handler = "ffmpeg"
extension = "ra"

[filetype.rar]
description = "RAR"
handler = "unrar"
header = [ 82, 97, 114, 33, 26, 7 ]
extension = "rar"

[filetype.rdf]
description = "RDF Document"
handler = "xml"
extension = "rdf"

[filetype.rm]
description = "RealMedia Video"
handler = "ffmpeg"
extension = "rm"

[filetype.rmvb]
description = "RealMedia Video (VBR)"
handler = "ffmpeg"
extension = "rmvb"

[filetype.rpm]
description = "RPM Package"
handler = "rpm"
extension = "rpm"

[filetype.rsn]
description = "RSN"
handler = "unrar"
container = "rar"
extension = "rsn"

[filetype.rss]
description = "RSS Feed"
handler = "xml"
extension = "rss"

[filetype.rv]
description = "RealVideo"
handler = "ffmpeg"
extension = "rv"

[filetype.sea]
description = "SEA archive"
handler = "lsar"
extension = "sea"

[filetype.shorten]
description = "Shorten Audio"
handler = "ffmpeg"
extension = "shn"

[filetype.sit]
description = "Stuffit archive"
handler = "lsar"
extension = "sit"

[filetype.speex]
description = "Speex Audio"
handler = "ffmpeg"
extension = "spx"

[filetype.sqlite3]
description = "SQLite3 Database"
handler = "sqlite3"
header = [ 83, 81, 76, 105, 116, 101, 32, 102, 111, 114, 109, 97, 116, 32, 51, 0 ]
extension = "sqlite3"

[filetype.sun_au]
description = "Sun Audio (with header)"
handler = "ffmpeg"
header = [ 46, 115, 110, 100 ]

[filetype.svg]
description = "SVG Image"
handler = "xml"
extension = "svg"

[filetype.svgz]
description = "SVG Image (GZip compressed)"
handler = "gzip"
container = "gzip"
extension = "svgz"

[filetype.tar]
description = "Tar Archive"
handler = "tar"
header_offset = 257
header = [ [ 117, 115, 116, 97, 114, 0, 48, 48 ], [ 117, 115, 116, 97, 114, 32, 32, 0 ] ]
extension = "tar"

[filetype.targa]
description = "Truevision TGA Image"
handler = "pil"
extension = "tga"

[filetype.tbz2]
description = "Tar Archive (BZip2 compressed)"
handler = "tar"
container = "bzip2"
extension = "tbz2"

[filetype.tgz]
description = "Tar Archive (GZip compressed)"
handler = "tar"
container = "gzip"
extension = "tgz"

[filetype.tiff]
description = "TIFF Image"
handler = "pil"
extension = [ "tif", "tiff" ]

[filetype.tlz]
description = "Tar Archive (.lzma compressed)"
handler = "tar"
container = "lzma"
extension = "tlz"

[filetype.txt]
description = "Plaintext"
handler = "txt"
extension = "txt"

[filetype.txz]
description = "Tar Archive (.xz compressed)"
handler = "tar"
container = "xz"
extension = "txz"

[filetype.uu]
description = "UUEncoded"
handler = "uuencode"
extension = [ "uu", "uue" ]

[filetype.voc]
description = "Soundblaster VOC Audio"
handler = "ffmpeg"
extension = "voc"

[filetype.wave]
description = "Microsoft Waveform Audio"
handler = "ffmpeg"
extension = "wav"

[filetype.wavpack]
description = "WavPack Audio"
handler = "ffmpeg"
extension = "wv"

[filetype.webm]
description = "WebM Video"
handler = "ffmpeg"
extension = "webm"

[filetype.webp]
description = "WebP Image"
handler = "pil"
extension = "webp"

[filetype.wma]
description = "Windows Media Audio"
handler = "ffmpeg"
container = "asf"
extension = "wma"

[filetype.wmv]
description = "Windows Media Video"
handler = "ffmpeg"
container = "asf"
extension = "wmv"

[filetype.xbm]
description = "X BitMap Image"
handler = "pil"
extension = "xbm"

[filetype.xlsm]
description = "Macro-enabled OOXML Workbook"
handler = "zip"
container = "zip"
extension = "xlsm"

[filetype.xlsx]
description = "OOXML Workbook"
handler = "zip"
container = "zip"
extension = "xlsx"

[filetype.xml]
description = "XML Data"
handler = "xml"
header = [ 60, 63, 120, 109, 108, 32 ]
extension = "xml"

[filetype.xpi]
description = "Mozilla XPI"
handler = "zip"
container = "zip"
extension = "xpi"

[filetype.xpm]
description = "X PixMap Image"
handler = "pil"
extension = "xpm"

[filetype.xz]
description = ".xz compressed"
handler = "lzma"
header = [ 253, 55, 122, 88, 90, 0 ]
extension = "xz"

[filetype.zip]
description = "Zip archive"
handler = "zip"
header = [ [ 80, 75, 3, 4 ], [ 80, 75, 5, 6 ], [ 80, 75, 7, 8 ] ]
extension = "zip"

[[override]]
path = "*/hts-cache/new.zip"
ignore = true
message = "Skipping intentionally broken HTTrack Zip file"

[[override]]
path = "*/.git"
ignore = true

# TODO: Decide how to indicate how thorough a handler is so something like
# "unpack the Zip container" isn't treated as equivalent to "unpack the Zip
# container and check the images inside the CBZ for corruption".

[handler.arj]
argv = [ "arj", "t" ]

[handler.cabextract]
argv = [ "cabextract", "-t" ]

# TODO: FFmpeg ignores too many errors. Find stricter options and better
#       verifiers for as many different formats as possible.
[handler.ffmpeg]
argv = [ "ffmpeg", "-f", "null", "-", "-i" ]

[handler.flac]
argv = [ "flac", "-t" ]

[handler.innoextract]
argv = [ "innoextract", "-t", "-g" ]

[handler.lsar]
argv = [ "lsar", "-t" ]

[handler.lzip]
argv = [ "lzip", "-t" ]

[handler.p7zip]
argv = [ "7z", "t" ]

[handler.pdftotext]
fail_if_stderr = "Error"
argv = [ "pdftotext", "{path}", "{devnull}" ]

[handler.rpm]
argv = [ "rpm", "--checksig" ]

[handler.unrar]
argv = [ "unrar", "t" ]

# TODO: Write a test suite to verify that validators are catching every readily
#       detectable way this config file could be malformed.
