name: Build and run test suite
on: [push, pull_request]
defaults:
    run:
        working-directory: verify_files
env:
    CARGO_TERM_COLOR: always
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
